create-batch --jobName TT_powheg_pythia8 --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_TT_powheg.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName DoubleEG_Run2016B --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_DoubleEG_Run2016B.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName DoubleEG_Run2016C --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_DoubleEG_Run2016C.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName DoubleEG_Run2016D --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_DoubleEG_Run2016D.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName DoubleEG_Run2016E --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_DoubleEG_Run2016E.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName DoubleEG_Run2016F --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_DoubleEG_Run2016F.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName DoubleEG_Run2016G --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_DoubleEG_Run2016G.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName DoubleEG_Run2016H_v3 --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_DoubleEG_Run2016H_v3.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName DoubleMuon_Run2016B --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_DoubleMuon_Run2016B.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName DoubleMuon_Run2016C --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_DoubleMuon_Run2016C.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName DoubleMuon_Run2016D --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_DoubleMuon_Run2016D.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName DoubleMuon_Run2016E --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_DoubleMuon_Run2016E.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName DoubleMuon_Run2016F --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_DoubleMuon_Run2016F.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName DoubleMuon_Run2016G --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_DoubleMuon_Run2016G.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName DoubleMuon_Run2016H_v3 --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_DoubleMuon_Run2016H_v3.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName MuonEG_Run2016B --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_MuonEG_Run2016B.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName MuonEG_Run2016C --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_MuonEG_Run2016C.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName MuonEG_Run2016D --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_MuonEG_Run2016D.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName MuonEG_Run2016E --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_MuonEG_Run2016E.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName MuonEG_Run2016F --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_MuonEG_Run2016F.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName MuonEG_Run2016G --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_MuonEG_Run2016G.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName MuonEG_Run2016H_v3 --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_MuonEG_Run2016H_v3.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
#create-batch --jobName TTTT_Signal --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/CATtoSSB/TTTT.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
#create-batch --jobName TTTT_Others --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/CATtoSSB/TTTT.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName DYJets --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_DYJets.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName ttW --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_ttW.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName ttZ --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_ttZ.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName WJets --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_WJets.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName WGtoLNuG --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_WGtoLNuG.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName WW --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_WW.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName WWW --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_WWW.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName SingleTop_tW --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_SingleTop_tW.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
create-batch --jobName SingleTbar_tW --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_SingleTbar_tW.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
#create-batch --jobName  --fileList $CMSSW_BASE/src/CATTools/CatAnalyzer/data/dataset/dataset_.txt --maxFiles 50 --cfg CATtoSSB_cfg.py
